# Generated by Django 2.0.1 on 2018-02-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailstaticCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_date', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=50, null=True)),
                ('manager', models.CharField(blank=True, db_column='Manager', max_length=50, null=True)),
                ('analyst', models.CharField(blank=True, db_column='Analyst', max_length=101, null=True)),
                ('logid', models.CharField(blank=True, max_length=15, null=True)),
                ('starttime_utc', models.BigIntegerField(blank=True, null=True)),
                ('scheduled_start', models.CharField(blank=True, db_column='Scheduled Start', max_length=50, null=True)),
                ('scheduled_stop', models.CharField(blank=True, db_column='Scheduled Stop', max_length=50, null=True)),
                ('interval_time', models.CharField(blank=True, db_column='Interval Time', max_length=8, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('total_interval_time', models.BigIntegerField(blank=True, db_column='Total Interval Time', null=True)),
                ('total_productive_status', models.TimeField(blank=True, db_column='Total Productive Status', null=True)),
                ('availability_adherence', models.DecimalField(blank=True, db_column='Availability Adherence', decimal_places=4, max_digits=41, null=True)),
                ('total_acd_time', models.TimeField(blank=True, db_column='Total ACD Time', null=True)),
                ('outbound_call', models.TimeField(blank=True, db_column='Outbound Call', null=True)),
                ('hold_time', models.TimeField(blank=True, db_column='Hold Time', null=True)),
                ('total_acw_time', models.TimeField(blank=True, db_column='Total ACW Time', null=True)),
                ('ring_time', models.TimeField(blank=True, db_column='Ring Time', null=True)),
                ('available_time', models.TimeField(blank=True, db_column='Available Time', null=True)),
                ('staffed_time', models.TimeField(blank=True, db_column='Staffed Time', null=True)),
                ('internal_aux_time', models.TimeField(blank=True, db_column='Internal AUX Time', null=True)),
                ('aux_default', models.TimeField(blank=True, db_column='AUX Default', null=True)),
                ('first_break', models.TimeField(blank=True, db_column='First Break', null=True)),
                ('second_break', models.TimeField(blank=True, db_column='Second Break', null=True)),
                ('training', models.TimeField(blank=True, db_column='Training', null=True)),
                ('lunch', models.TimeField(blank=True, db_column='Lunch', null=True)),
                ('meeting', models.TimeField(blank=True, db_column='Meeting', null=True)),
                ('personal', models.TimeField(blank=True, db_column='Personal', null=True)),
                ('project', models.TimeField(blank=True, db_column='Project', null=True)),
                ('case_management', models.TimeField(blank=True, db_column='Case Management', null=True)),
                ('third_break', models.TimeField(blank=True, db_column='Third Break', null=True)),
                ('coaching', models.TimeField(blank=True, db_column='Coaching', null=True)),
                ('outbound_voice', models.TimeField(blank=True, db_column='Outbound Voice', null=True)),
                ('get_next', models.TimeField(blank=True, db_column='Get Next', null=True)),
                ('vip_escalation', models.TimeField(blank=True, db_column='VIP Escalation', null=True)),
                ('handling_escalation', models.TimeField(blank=True, db_column='Handling Escalation', null=True)),
                ('acdcalls', models.SmallIntegerField(blank=True, null=True)),
                ('da_acdcalls', models.SmallIntegerField(blank=True, null=True)),
                ('total_acd_other_time', models.TimeField(blank=True, db_column='Total ACD Other Time', null=True)),
                ('total_acd_aux_out_time', models.TimeField(blank=True, db_column='Total ACD/AUX Out Time', null=True)),
                ('total_acd_aux_in_time', models.TimeField(blank=True, db_column='total ACD/AUX In Time', null=True)),
                ('total_aux_in_time', models.TimeField(blank=True, db_column='Total AUX in Time', null=True)),
            ],
            options={
                'db_table': 'availstatic_copy',
                'managed': False,
            },
        ),
    ]
